import logging
import asyncio
import platform
import json
import base64
import urllib.request
import http.client
from typing import Optional, Any
from llm.router import ModelTier
from llm.action_normalizer import ActionNormalizer, Action
from sandbox.sandbox_aci import SandboxACI

logger = logging.getLogger("desktopenv.agent")

class ExecutorAgent:
    """Handles translating sub-goals into actions using a multi-tier LLM/ShowUI waterfall,

    coordinate grounding, and execution in the sandbox environment.
    """

    def __init__(self, config, router, memory, compressor, verifier_agent) -> None:
        self.config = config
        self.router = router
        self.memory = memory
        self.compressor = compressor
        self.verifier_agent = verifier_agent
        self._action_normalizer = ActionNormalizer()
        self.last_parse_mode = "claude_gpt"
        self._showui = None
        self._showui_load_attempted = False
        self._uia_layer = None
        self.escalation_context = ""
        self.task_messages: list[dict] = []

    def reset(self) -> None:
        """Resets execution session state."""
        self.last_parse_mode = "claude_gpt"
        self.escalation_context = ""
        self.task_messages = []
        if self._showui is not None:
            try:
                self._showui.unload()
            except Exception:
                pass
            self._showui = None
        self._showui_load_attempted = False

    async def execute(
        self,
        sub_goal: str,
        screenshot: bytes,
        acc_before: Optional[dict],
        step: int,
        task,
        action_history: list[str]
    ) -> tuple[dict, str, Action]:
        """
        Runs the execution waterfall to predict the next action, normalizes it,
        and refines the coordinates if necessary.
        Returns: (step_info, action_str, normalized_action)
        """
        # 1. Attempt UIA-based execution BEFORE ShowUI (additive Windows-only layer)
        if self.config.use_windows_uia and platform.system() == "Windows":
            uia_result = await self._attempt_uia_execution(sub_goal, screenshot)
            if uia_result and uia_result.success:
                # UIA executed the action directly — skip ShowUI coordinate path
                logger.info(f"[ExecutorAgent/UIA] SUCCESS: {uia_result.action_taken}")
                action = Action(
                    action_type="uia_completed",
                    target_description=uia_result.action_taken,
                    element_id=None,
                    params={
                        "action_taken": uia_result.action_taken,
                        "controls_found": uia_result.controls_found,
                    }
                )
                step_info = {"reflection": f"[UIA] {uia_result.action_taken}"}
                action_str = f"[UIA] {uia_result.action_taken}"
                return step_info, action_str, action
            else:
                if uia_result:
                    logger.info(f"[ExecutorAgent/UIA] UIA attempt failed: {uia_result.error}. Falling through to ShowUI...")
                else:
                    logger.info("[ExecutorAgent/UIA] UIA attempt returned None. Falling through to ShowUI...")

        # 2. Call internal _execute_step to retrieve next action and reflection (ShowUI / Groq path)
        step_info, actions = await self._execute_step(sub_goal, {"screenshot": screenshot, "acc": acc_before}, task, action_history)

        if not actions:
            raise RuntimeError("No action generated by prediction.")

        action_str = actions[0]
        parse_mode = self.last_parse_mode
        action = self._action_normalizer.normalize(action_str, parse_mode)
        logger.info(f"[ExecutorAgent] Parsed Action: Type={action.type} | Target={action.target_description} | Element={action.element_id}")

        # 3. Coordinate Verification & Refinement
        if action.type in ("click", "type", "scroll", "drag_and_drop") and (
            "x_norm" in action.params or "x" in action.params or "x1_norm" in action.params
        ):
            action = await self.verifier_agent.verify_coordinate(
                action=action,
                screenshot=screenshot,
                task=sub_goal,
            )

        return step_info, action_str, action

    async def run_in_sandbox(self, action: Action, sandbox: SandboxACI) -> None:
        """Executes the action inside the sandbox."""
        if action.type == "uia_completed":
            logger.info("[ExecutorAgent] Skipping sandbox execution since UIA already executed the action.")
            return
        await sandbox.execute(action)

    async def _execute_step(self, instruction: str, obs: dict, task, action_history: list[str]) -> tuple[dict, list[str]]:
        task_type = "desktop"
        if "web" in instruction.lower() or "browser" in instruction.lower() or "http" in instruction.lower():
            task_type = "web"

        is_escalated = task.is_escalated or self.router.current_tier == ModelTier.CLOUD

        # Build system prompt with task description injected + memory context
        system_prompt = self.router.get_system_prompt(task_type, SandboxACI).replace(
            "TASK_DESCRIPTION", instruction
        )
        facts = self.memory.get_context_for_task(instruction, task.session_id)
        if facts and "No relevant memories" not in facts:
            system_prompt += f"\n\nHistorical Facts / Working Memory:\n{facts}"
        
        if self.escalation_context:
            system_prompt += f"\n\nContext from previous attempts (Mermaid task graph):\n{self.escalation_context}"
            self.escalation_context = ""  # consumed

        screenshot = obs.get("screenshot", b"")

        # Cloud escalation path
        if is_escalated or self.router.current_tier == ModelTier.CLOUD:
            try:
                self.last_parse_mode = "groq"
                logger.info(f"[ExecutorAgent/Groq Escalation] Using {self.config.groq_brain_model} as escalated Actor")
                response_text = await self._call_groq_actor(
                    screenshot, instruction, action_history, model=self.config.groq_brain_model
                )
                if response_text:
                    logger.info(f"[ExecutorAgent/Groq Escalation] response (first 300 chars): {response_text[:300]}")
                    return {"reflection": response_text[:300]}, [response_text]
            except Exception as e:
                logger.warning(f"[ExecutorAgent/Groq Escalation] Failed: {e}. Falling through to local tiers.")

        response_text: Optional[str] = None

        # Tier 1 — ShowUI-2B
        if self._showui is None and not self._showui_load_attempted:
            try:
                from llm.showui_agent import ShowUIAgent
                self._showui = ShowUIAgent(self.config.showui_model_path)
                self._showui_load_attempted = True
                logger.info("[ExecutorAgent/ShowUI] Agent instantiated — weights load on first inference call.")
            except Exception as err:
                logger.warning(f"[ExecutorAgent/ShowUI] Could not instantiate agent: {err}. Skipping Tier 1.")
                self._showui_load_attempted = True

        if self._showui is not None and response_text is None:
            try:
                self.last_parse_mode = "showui"
                response_text = await self._showui.get_action(
                    screenshot=screenshot,
                    task=instruction,
                    task_type=task_type,
                    history=list(action_history),
                )
                logger.info(f"[ExecutorAgent/ShowUI] Response: {response_text[:200] if response_text else 'empty'}")
            except Exception as err:
                logger.warning(f"[ExecutorAgent/ShowUI] Inference failed: {err}. Disabling and falling through to Ollama.")
                try:
                    self._showui.unload()
                except Exception:
                    pass
                self._showui = None
                response_text = None

        # Tier 2 — qwen3-vl:8b via Ollama
        if self.config.ollama_actor_model and not response_text:
            try:
                self.last_parse_mode = "groq"
                logger.info(f"[ExecutorAgent/Ollama Actor] Calling {self.config.ollama_actor_model}")
                response_text = await self._call_ollama_actor(screenshot, instruction, action_history)
                logger.info(f"[ExecutorAgent/Ollama Actor] Response: {response_text[:200] if response_text else 'empty'}")
            except Exception as err:
                logger.warning(f"[ExecutorAgent/Ollama Actor] Inference failed: {err}. Falling through to Groq.")
                response_text = None

        # Tier 3 — Groq cloud (fallback when local models unavailable)
        if self.config.groq_api_key and not response_text:
            try:
                self.last_parse_mode = "groq"
                logger.info(f"[ExecutorAgent/Groq Actor] Local tiers failed — calling {self.config.groq_actor_model}")
                response_text = await self._call_groq_actor(screenshot, instruction, action_history)
            except Exception as err:
                logger.warning(f"[ExecutorAgent/Groq Actor] Inference failed: {err}. Falling through to Fara.")
                response_text = None

        # Tier 4 — Fara-7B text-only
        if not response_text:
            try:
                self.last_parse_mode = "fara"
                if not self.task_messages:
                    screen_desc = await self._describe_screen_with_claude(screenshot)
                    self.task_messages.append({
                        "role": "user",
                        "content": (
                            f"Task: {instruction}\n\n"
                            f"Current screen:\n{screen_desc}\n\n"
                            "Analyze the screen and output your next action as a JSON object."
                        )
                    })
                response_text = await self._call_local_llm(system_prompt, self.task_messages)
                self.task_messages.append({"role": "assistant", "content": response_text})
            except Exception as err:
                logger.error(f"[ExecutorAgent/Fara] All tiers exhausted. Final error: {err}")
                err_msg = str(err)[:120].replace('"', "'")
                return (
                    {"reflection": f"All LLM tiers failed: {err}"},
                    [f'{{"action": "fail", "reason": "LLM unavailable: {err_msg}"}}'],
                )

        if not response_text:
            return (
                {"reflection": "Empty response from all tiers"},
                ['{"action": "fail", "reason": "LLM returned empty response"}'],
            )

        logger.info(f"[ExecutorAgent] LLM response (first 300 chars): {response_text[:300]}")
        return {"reflection": response_text[:300]}, [response_text]

    async def _call_groq_actor(self, screenshot: bytes, instruction: str, action_history: list[str], model: str | None = None) -> str:
        model = model or self.config.groq_actor_model
        if not self.config.groq_api_key:
            raise RuntimeError("GROQ_API_KEY not set — cannot use Groq")

        system_prompt = (
            "You are a precise Windows desktop automation agent.\n"
            "You will receive a screenshot and a task. Analyze the screen carefully.\n\n"
            "Output ONLY a single JSON object — no markdown, no explanation, nothing else.\n\n"
            "Available actions:\n"
            '{"thoughts": "your reasoning", "action": "click",  "element_id": "describe what to click"}\n'
            '{"thoughts": "your reasoning", "action": "type",   "element_id": "describe the input field", "text": "text to type"}\n'
            '{"thoughts": "your reasoning", "action": "scroll", "element_id": "describe the scroll area", "direction": "up", "amount": 3}\n'
            '{"thoughts": "your reasoning", "action": "hotkey", "key": "ctrl+c"}\n'
            '{"thoughts": "your reasoning", "action": "navigate", "url": "https://..."}\n'
            '{"thoughts": "your reasoning", "action": "done",   "thoughts": "what was achieved"}\n'
            '{"thoughts": "your reasoning", "action": "fail",   "reason": "why it cannot be done"}\n\n'
            "Rules:\n"
            "- element_id must describe something visually present on the screenshot\n"
            "- For clicks, be specific: 'blue Submit button at bottom-right', not just 'button'\n"
            "- To search or launch local apps/tools, use hotkey 'win' to open the Start menu, type the app name, and send hotkey 'enter'\n"
            "- Output ONLY the JSON object on a single line"
        )

        history_text = ""
        if action_history:
            lines = "\n".join(f"  {i+1}. {h}" for i, h in enumerate(action_history[-6:]))
            history_text = f"\n\nPrevious actions taken:\n{lines}"

        b64 = base64.standard_b64encode(screenshot).decode("utf-8")

        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {
                            "type": "text",
                            "text": f"Task: {instruction}{history_text}\n\nOutput your next action as JSON:"
                        },
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/png;base64,{b64}"}
                        }
                    ]
                }
            ],
            "temperature": 0.0,
            "max_tokens": 256,
        }
        data_bytes = json.dumps(payload).encode("utf-8")

        def _do_request() -> str:
            import urllib.request
            import time
            max_retries = 3
            backoff = 2.0
            for attempt in range(max_retries):
                try:
                    req = urllib.request.Request(
                        "https://api.groq.com/openai/v1/chat/completions",
                        data=data_bytes,
                        headers={
                            "Content-Type": "application/json",
                            "Authorization": f"Bearer {self.config.groq_api_key}",
                            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                        },
                        method="POST",
                    )
                    with urllib.request.urlopen(req, timeout=30.0) as res:
                        return res.read().decode("utf-8")
                except urllib.error.HTTPError as http_err:
                    if http_err.code == 429 and attempt < max_retries - 1:
                        logger.warning(f"Groq Actor API returned 429 (Too Many Requests). Retrying in {backoff}s...")
                        time.sleep(backoff)
                        backoff *= 2.0
                        continue
                    raise http_err

        loop = asyncio.get_running_loop()
        res_str = await loop.run_in_executor(None, _do_request)
        data = json.loads(res_str)
        return data["choices"][0]["message"]["content"].strip()

    async def _call_ollama_actor(self, screenshot: bytes, instruction: str, action_history: list[str]) -> str:
        model = self.config.ollama_actor_model
        if not model:
            raise RuntimeError("OLLAMA_ACTOR_MODEL not configured")

        base_url = self.config.local_vllm_url.rstrip("/")

        system_prompt = (
            "You are a precise Windows desktop automation agent.\n"
            "You will receive a screenshot and a task. Analyze the screen carefully.\n\n"
            "Output ONLY a single JSON object — no markdown, no explanation, nothing else.\n\n"
            "COORDINATE SYSTEM: x_norm and y_norm are normalized screen positions (0.0 = left/top edge, 1.0 = right/bottom edge).\n"
            "You MUST include x_norm and y_norm for click, type, and scroll actions.\n\n"
            "Available actions:\n"
            '{"thoughts": "...", "action": "click",    "x_norm": 0.5, "y_norm": 0.9}\n'
            '{"thoughts": "...", "action": "type",     "x_norm": 0.5, "y_norm": 0.9, "text": "text to type"}\n'
            '{"thoughts": "...", "action": "scroll",   "x_norm": 0.5, "y_norm": 0.5, "direction": "down", "amount": 3}\n'
            '{"thoughts": "...", "action": "hotkey",   "key": "win+r"}\n'
            '{"thoughts": "...", "action": "navigate", "url": "https://youtube.com"}\n'
            '{"thoughts": "...", "action": "done"}\n'
            '{"thoughts": "...", "action": "fail",     "reason": "why it cannot be done"}\n\n'
            "Rules:\n"
            "- x_norm: horizontal position (0.0=left, 0.5=center, 1.0=right)\n"
            "- y_norm: vertical position (0.0=top, 0.5=middle, 1.0=bottom)\n"
            "- Be precise: a taskbar icon is at y_norm≈0.97, address bar at y_norm≈0.06\n"
            "- To search or launch local apps/tools, use hotkey 'win' to open the Start menu, type the app name, and send hotkey 'enter'\n"
            "- Output ONLY the JSON object on a single line"
        )

        history_text = ""
        if action_history:
            lines = "\n".join(f"  {i+1}. {h}" for i, h in enumerate(action_history[-6:]))
            history_text = f"\n\nPrevious actions taken:\n{lines}"

        b64 = base64.standard_b64encode(screenshot).decode("utf-8")

        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {
                    "role": "user",
                    "content": [
                        {"type": "text", "text": f"Task: {instruction}{history_text}\n\nOutput your next action as JSON:"},
                        {"type": "image_url", "image_url": {"url": f"data:image/png;base64,{b64}"}},
                    ],
                },
            ],
            "temperature": 0.6,
            "max_tokens": 2048,
            "think": False,
        }
        data_bytes = json.dumps(payload).encode("utf-8")

        def _do_request() -> str:
            import urllib.request
            req = urllib.request.Request(
                f"{base_url}/chat/completions",
                data=data_bytes,
                headers={"Content-Type": "application/json"},
                method="POST",
            )
            with urllib.request.urlopen(req, timeout=180.0) as res:
                return res.read().decode("utf-8")

        loop = asyncio.get_running_loop()
        res_str = await loop.run_in_executor(None, _do_request)
        data = json.loads(res_str)
        return data["choices"][0]["message"]["content"].strip()

    async def _describe_screen_with_claude(self, screenshot: bytes) -> str:
        if not screenshot or not self.config.groq_api_key:
            return "Screen state unknown — no screenshot available."
        try:
            b64 = base64.standard_b64encode(screenshot).decode("utf-8")
            payload = {
                "model": self.config.groq_brain_model,
                "messages": [{
                    "role": "user",
                    "content": [
                        {
                            "type": "image_url",
                            "image_url": {"url": f"data:image/png;base64,{b64}"},
                        },
                        {
                            "type": "text",
                            "text": (
                                "Describe this computer screen in 3-5 sentences for a computer-use agent. "
                                "Include: which application is in focus, key UI elements and their approximate "
                                "screen positions (top-left, top-center, etc.), any text visible in the address "
                                "bar, title bar, or active input field. Be specific. Do not suggest actions."
                            ),
                        },
                    ],
                }],
                "temperature": 0.0,
                "max_tokens": 300,
            }
            data_bytes = json.dumps(payload).encode("utf-8")

            def _req() -> str:
                import time
                max_retries = 3
                backoff = 2.0
                for attempt in range(max_retries):
                    try:
                        req = urllib.request.Request(
                            "https://api.groq.com/openai/v1/chat/completions",
                            data=data_bytes,
                            headers={
                                "Content-Type": "application/json",
                                "Authorization": f"Bearer {self.config.groq_api_key}",
                                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                            },
                            method="POST",
                        )
                        with urllib.request.urlopen(req, timeout=15.0) as res:
                            return json.loads(res.read().decode("utf-8"))["choices"][0]["message"]["content"]
                    except urllib.error.HTTPError as http_err:
                        if http_err.code == 429 and attempt < max_retries - 1:
                            logger.warning(f"Groq Vision Desc API returned 429 (Too Many Requests). Retrying in {backoff}s...")
                            time.sleep(backoff)
                            backoff *= 2.0
                            continue
                        raise http_err

            loop = asyncio.get_running_loop()
            description = await loop.run_in_executor(None, _req)
            logger.info(f"[ExecutorAgent/Groq VLM] Screen description: {description[:150]}")
            return description
        except Exception as e:
            logger.warning(f"Groq screen description failed: {e}")
            return f"Screen state unknown (vision call failed: {e})"

    async def _call_local_llm_raw(self, system_prompt: str, messages: list[dict], max_tokens: int = 512) -> str:
        payload = {
            "model": self.config.fara_model_id,
            "messages": [{"role": "system", "content": system_prompt}] + messages,
            "temperature": 0.0,
            "max_tokens": max_tokens,
        }
        data_bytes = json.dumps(payload).encode("utf-8")
        url = f"{self.config.local_vllm_url.rstrip('/')}/chat/completions"

        def _do_request() -> str:
            import urllib.error
            for attempt in range(2):
                req = urllib.request.Request(
                    url,
                    data=data_bytes,
                    headers={
                        "Content-Type": "application/json",
                        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
                    },
                    method="POST",
                )
                try:
                    with urllib.request.urlopen(req, timeout=20.0) as res:
                        return res.read().decode("utf-8")
                except urllib.error.HTTPError as http_err:
                    body = http_err.read().decode("utf-8", errors="replace")
                    raise RuntimeError(f"HTTP {http_err.code} from LM Studio: {body[:400]}")
                except (http.client.RemoteDisconnected, ConnectionResetError) as conn_err:
                    if attempt == 0:
                        logger.warning(f"LM Studio dropped connection (attempt {attempt+1}), retrying in 3s: {conn_err}")
                        import time; time.sleep(3)
                        continue
                    raise RuntimeError(f"LM Studio dropped connection after retry: {conn_err}")
            raise RuntimeError("LM Studio request failed after all attempts")

        loop = asyncio.get_running_loop()
        res_str = await loop.run_in_executor(None, _do_request)
        data = json.loads(res_str)
        return data["choices"][0]["message"]["content"]

    async def _call_local_llm(self, system_prompt: str, messages: list[dict]) -> str:
        def estimate_tokens(msgs: list[dict], sys_prompt: str) -> int:
            return (sum(len(m["content"]) for m in msgs) + len(sys_prompt)) // 4

        estimated = estimate_tokens(messages, system_prompt)
        budget = min(self.config.local_task_token_budget, 4096)

        if estimated > int(budget * 0.70) and len(messages) > 6:
            logger.info(f"[ExecutorAgent/History Compression] Context size {estimated} exceeds 70% of budget {budget}. Summarizing history...")
            first_msg = messages[0]
            recent_msgs = messages[-4:]
            middle_msgs = messages[1:-4]

            summary_payload = ""
            for m in middle_msgs:
                role = "Agent" if m["role"] == "assistant" else "User/Screen"
                summary_payload += f"{role}: {m['content']}\n\n"

            summarize_prompt = (
                "You are an assistant. Summarize the following sequential steps taken by a computer automation agent "
                "in 3 sentences or less, listing what was attempted, what succeeded, and what failed:\n\n"
                f"{summary_payload}"
            )

            try:
                summary = await self._call_local_llm_raw(
                    system_prompt="You are a precise summarization assistant.",
                    messages=[{"role": "user", "content": summarize_prompt}],
                    max_tokens=150
                )
                logger.info(f"[ExecutorAgent/History Compression] Compression summary: {summary}")
                compressed_messages = [
                    first_msg,
                    {"role": "user", "content": f"Recap of previous attempts:\n{summary}"}
                ] + recent_msgs
                messages[:] = compressed_messages
            except Exception as comp_err:
                logger.warning(f"[ExecutorAgent/History Compression] History summarization failed: {comp_err}. Falling back to standard slicing.")
                first_msg = messages[0]
                recent_msgs = messages[-4:]
                messages[:] = [first_msg] + recent_msgs
        elif len(messages) > 10:
            messages[:] = [messages[0]] + messages[-9:]

        return await self._call_local_llm_raw(system_prompt, messages, max_tokens=512)

    async def _attempt_uia_execution(self, sub_goal: str, screenshot: bytes):
        try:
            if self._uia_layer is None:
                from windows_only.uia_layer import WindowsUIALayer
                self._uia_layer = WindowsUIALayer()
                if not self._uia_layer.is_available():
                    logger.warning("[ExecutorAgent/UIA] WindowsUIALayer initialization failed. Disabling UIA.")
                    self.config.use_windows_uia = False
                    return None
                logger.info("[ExecutorAgent/UIA] WindowsUIALayer initialized successfully.")

            result = await self._uia_layer.attempt_uia_step(
                sub_goal=sub_goal,
                screenshot=screenshot,
                groq_api_key=self.config.groq_api_key,
                groq_model=self.config.groq_brain_model,
            )
            return result
        except Exception as e:
            logger.warning(f"[ExecutorAgent/UIA] _attempt_uia_execution failed: {e}")
            return None
